language: python
python:
  - "2.7"

install:
  - pip install pytest pytest-cov
  - pip install coveralls==1.1
  - pip install ptrace resource tox tox-travis

script:
  - py.test --cov codeMarble

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
      - ngh3053@gmail.com
    on_success: always
    on_failure: always
