language: python
python:
  - "2.7"

install:
  - pip install ptrace resource coveralls tox tox-travis

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
      - ngh3053@gmail.com
    on_success: always
    on_failure: always
