language: python
python:
  - "2.7"

install:
  - pip install pytest
  - pip install pytest-cov==2.4.0
  - pip install coveralls==1.1
  - pip install ptrace resource tox tox-travis

script:
  - py.test --cov codeMarble test_api.py

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
      - ngh3053@gmail.com
    on_success: always
    on_failure: always
