language: python
python:
  - "2.7"

install:
  #- pip install ...
  #- python setup.py install

script:
#

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
    on_success: always
    on_failure: always